- name: Start MariaDB container
  community.docker.docker_container:
    name: "{{ db_container }}"
    image: "{{ mariadb_image }}"
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_root_pw }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_pw }}"
      MYSQL_DATABASE: "{{ db_name }}"
    published_ports:
      - "{{ mariadb_port }}:{{ mariadb_port }}"
    volumes:
      - "/var/lib/{{ db_container }}:/var/lib/mysql"

- name: Start WordPress container
  community.docker.docker_container:
    name: "{{ wp_container }}"
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    links:
      - "{{ db_container }}:db"
    env:
      WORDPRESS_DB_HOST: "db:{{ mariadb_port }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_pw }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_SITEURL', 'http://{{ ansible_host }}' );
        define( 'WP_HOME', 'http://{{ ansible_host }}' );
    published_ports:
      - "{{ wp_port }}:80"
    volumes:
      - "/var/www/wordpress:/var/www/html"