# This task starts two Docker containers: MySQL and Joomla.
# The MySQL container is configured with a root password, a database, 
# and a user for Joomla. It exposes port 3306.
# The Joomla container connects to the MySQL container using environment 
# variables and a link. It exposes port 80 for web access.
# Both containers are set to always restart to ensure availability.
- name: Start MySQL container
  docker_container:
    name: mysql
    image: mysql:8.0.13
    env:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomlapassword
    ports:
      - '3306:3306'
    state: started
    restart_policy: always

- name: Start Joomla container
  docker_container:
    name: joomla
    image: joomla:latest
    env:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomlapassword
      JOOMLA_DB_NAME: joomla
    links:
      - mysql:mysql
    ports:
      - '80:80'
    state: started
    restart_policy: always