# This playbook performs the following tasks on a Windows 11 VM:
# 1. Prompts for user input to create a new user with specified groups and password.
# 2. Ensures the specified groups (finance, it, management) exist.
# 3. Creates a user and assigns them to the specified groups.
# 4. Creates a directory at C:\management.
# 5. Generates a file in the directory using a Jinja2 template.
# 6. Installs Git using Chocolatey.
---
- name: Add user, groups and programs
  hosts: win11vm
  gather_facts: no
  vars_prompt:
  - name: username
    prompt: Username
    private: no
  - name: password
    prompt: password
    private: yes
  - name: groepen
    prompt: Welke groepen moet deze gebruiker lid van zijn(gebruikers, finance, it, management) gescheiden door komma's)?
    private: no

  tasks:
    - name: Create all groups
      ansible.windows.win_group:
        name: "{{ item }}"
        state: present
      loop:
        - finance
        - it
        - management

    - name: Create user
      ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: "{{ groepen }}"

    - name: create C:\management
      ansible.windows.win_file:
        state: directory
        path: C:\management

    - name: Create a file from a Jinja2 template
      ansible.windows.win_template:
        src: windows_template.j2
        dest: C:\management\windows_file

    - name: install git
      win_chocolatey:
        name: git
        state: present