# This playbook deploys an Nginx load balancer using Docker on the specified host.
# It performs the following tasks:
# 1. Renders an nginx.conf file from a template, using inventory data.
# 2. Removes any existing Docker container named "nginx" to avoid conflicts.
# 3. Starts a new Nginx container with the specified configuration, 
#    exposing port 80 and mounting the generated nginx.conf as read-only.
---
- name: Deploy Nginx load balancer via Docker
  hosts: KlantA_Test_1
  become: true

  tasks:
    - name: Render nginx.conf from template
      ansible.builtin.template:
        src: "nginx.conf"
        dest: "{{ host_nginx_conf }}"
      # This builds the nginx.conf file with the IP addresses from your inventory

    - name: Remove any existing container with the same name
      community.docker.docker_container:
        name: "nginx"
        state: absent
      ignore_errors: true

    - name: Start the Nginx load balancer container
      community.docker.docker_container:
        name: "nginx"
        image: "nginx:1.27.4-alpine-slim"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        volumes:
          - "/tmp/nginx.conf:/etc/nginx/nginx.conf:ro"
      # Mount the generated configuration file into the container as read-only
