---
- name: Create users in Active Directory
  hosts: windows_servers
  gather_facts: no
  vars_files:
    - users.yml

  tasks:
    - name: Create users
      win_domain_user:
        name: "{{ item.firstname }}.{{ item.lastname }}"
        password: "{{ item.password }}"
        state: present
        password_never_expires: no
        user_cannot_change_password: no
        must_change_password: yes
      loop: "{{ users }}"
