# This playbook is used to deploy a load balancer for the production environment.
# It targets the host group "KlantB_Prod_1" and requires elevated privileges (become: true).
# The variable "webserver_ips" specifies the backend web server IPs for the load balancer.
# The "loadbalancer" role is applied to configure the load balancer.
---
- name: Deploy loadbalancer for production environment
  hosts: KlantB_Prod_1
  become: true
  vars:
    webserver_ips:
      - 54.83.227.72
      - 54.158.207.170
  roles:
    - loadbalancer
